# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.6
    - CONFIG=osx_python3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "qkpUxUblrLvY773817WylftMUKEzdOnj2F1U564tF43t6H4X5SJpb8no1hzJRUkrkw4d9sXPk10mbckBWRNHSt3vuL30uMhzzSFuumJ+9gDjULIJpPZYuqnuC6zmlyUKEn/gsbZUSE2rvaEd5pdKtI65NFdW2au3YqrLLhtMSmlsQnVq5bwBXWb4dGuJ/6jr6m3tSUnC6mZVSNkrRRR8zswxZ35uD6jQPeJoqFnktWxJCIEO5CzUT+EPOySCX68Cl7ZJqPRuDRTgXWRSLmE0mChmtxCEX0GnPNClc4Srj3K4yRbG5MZ7e9lSQqewuZ1coPdFqDdByKmx7qVDQr2x7b/XJuhznSBnxHNNzOPkER7lupo61zPDU3I7C2r5uvQMldhWvMRJ0fC3z0YBwv1Z8plCsswSyfnhUVAv5K2u7Xqhpyjh4TGlZnFB5rR8XzQdbpF6Fd92OD0oh9+qpHaouehRRDoav7v1wxHGNYrz30jaKqf9yx6HjGp3hPQ3ofaJYOGBM1ExU57axrq4X1DTgANxM/vcb11b3NE50gNYhW+GjCrDRLm326zBab2oI7Q45WT2yQcWnTrXyznb1O8G4DOSMVWChs3TYedCbyfFEp4L/FZm3KoyorAJ8XqQgDFWiytFRWqchUV0a4k91sVbR7b/NKBGnjzpf1MYwEjNfio="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
