travis:
  secure:
    BINSTAR_TOKEN: XC5I9k/AWangEN9bTDXYzVpMpUOZzEvCNaSUe3NCkZ4+ZdYv7g/l37HToAL7nuc0JuuQPs3fAfGUORRfj+dcQwT7US00P9Im/PzxkEyJZmB0HmGwj9zsDxzc3wLzM1xOjDuwUjn5lT2TEJjUru/ubPQko4O4L4S/nXQPhsx3SQ17nlxduD5fzhU+zCeyoAHveYCEX0d1lsrwyZzD+rI90rpBbqqVHMtP94RhOLE4ZY9ZsO0J9TC/cFhJ3WSyQHbLw5w+Jv34MO4l41yCt1NJkNs25z+RUp2vXj5iWLHJl8n6W7MiiSzeWYE9pJsXJauALs+cPNCQcxFBbL5+vvY+8IE01KMsmmFF+1wVBdgbGa2yGqDiOxa6D54PvDm3aRWgTMKIt9wy+dFt5m73XWhUArsaV7mcEzfucujQXgDdEHVk6A7c698uhdll2SlJBl2CsrMbOsFoy9go4Ec/8tW7USmxEwowjh/Nfho5DrGm/HGDO79lBlnyUrDZ6gh6RRWJSayCxdEbkC9FjP8jW5iD8oGsQk3URWOnFgzDB9BBebTL4mlwKR8wuNtg/On7AiR0P6CR8NhmCZOxm7l5W8VVTe83ke094agCVTfurLMkBaaBGtf+f+vT1tu08ARp5cwi0r+MWiGbUYmgX/JJIBUb9ebagNYkwpnE2XM/e+x1rSk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
