travis:
  secure:
    BINSTAR_TOKEN: qkpUxUblrLvY773817WylftMUKEzdOnj2F1U564tF43t6H4X5SJpb8no1hzJRUkrkw4d9sXPk10mbckBWRNHSt3vuL30uMhzzSFuumJ+9gDjULIJpPZYuqnuC6zmlyUKEn/gsbZUSE2rvaEd5pdKtI65NFdW2au3YqrLLhtMSmlsQnVq5bwBXWb4dGuJ/6jr6m3tSUnC6mZVSNkrRRR8zswxZ35uD6jQPeJoqFnktWxJCIEO5CzUT+EPOySCX68Cl7ZJqPRuDRTgXWRSLmE0mChmtxCEX0GnPNClc4Srj3K4yRbG5MZ7e9lSQqewuZ1coPdFqDdByKmx7qVDQr2x7b/XJuhznSBnxHNNzOPkER7lupo61zPDU3I7C2r5uvQMldhWvMRJ0fC3z0YBwv1Z8plCsswSyfnhUVAv5K2u7Xqhpyjh4TGlZnFB5rR8XzQdbpF6Fd92OD0oh9+qpHaouehRRDoav7v1wxHGNYrz30jaKqf9yx6HjGp3hPQ3ofaJYOGBM1ExU57axrq4X1DTgANxM/vcb11b3NE50gNYhW+GjCrDRLm326zBab2oI7Q45WT2yQcWnTrXyznb1O8G4DOSMVWChs3TYedCbyfFEp4L/FZm3KoyorAJ8XqQgDFWiytFRWqchUV0a4k91sVbR7b/NKBGnjzpf1MYwEjNfio=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
